### ISSUE TITLE
Royalty tests to receive amount for artists

### ISSUE THREAD

**Issue by yogk** [rarible/protocol-contracts#135]
hello,

Most of the test examples on royalties show how to save, modify and get the royalties associated with the token.
ie. the royalties are being saved or updated and then using get royalties e.x. royaltiesRegistryTest._getRoyalties(), you get the royalties associated with the token ID.

However, there is no example in any of the royalty folders that shows "when does the Artist actually receive the royalty amount after the successful transfer of token from owner A to B" (say ERC721 transfer, after calling,  safeTransferFrom(A, B, token ID)). 

Which function in the rarible royalty protocol is responsible to pay the royalty amount to the artist or how is it handled in rarible is not tested.

Thanks.!

**Comment by SKonstantinS** [comment]
Hello, thanks for issue.
As soon as possible I`ll try to understand the problem and write a tests.

**Comment by SKonstantinS** [comment]
Hi @yogk,
1. We already have tests for setting and checking royalties amount after transfer
for Example there: exchange-v2/test/v2/RaribleManager.test.js (Line 512) test block `exchange-v2/test/v2/RaribleManager.test.js`

and there: exchange-v2/test/v2/ExchangeV2.rarible.test.js Line 810 `describe("Exchange with Royalties", () => {`
We don`t check balance of royalties recipients in royalties-registry, because we made simple union test for checking set and receive royalties are equal.
2. `Which function in the rarible royalty protocol is responsible to pay the royalty amount to the artist`
This function is `getRoyalties(address token, uint tokenId)`, and we check it tests.

**Comment by yogk** [comment]
Ok, I see it is part of exchange-V2 and not the royalty folder. Thanks a lot for the info.
I will close this issue.
